class RRF:
    def __init__(self):
        self.query = {
            "retriever": {
                "rrf": {
                    "retrievers": [],
                }
            }
        }

    def add_retrievers(self, retrievers):
        for retriver in retrievers:
            self.query["retriever"]["rrf"]["retrievers"].append(retriver.get_query())
        return self

    def get_query(self):
        return self.query


class RRF_Retriever:
    def __init__(self):
        self.query = {"standard": {"query": {}}}

    def get_query(self):
        return self.query


class RRF_Keyword_Retriever(RRF_Retriever):
    def __init__(self, item_name="keyword", keywords=""):
        super().__init__()
        query = {"terms": {item_name: keywords}}
        self.query["standard"]["query"] = query


class RRF_Match_Retriever(RRF_Retriever):
    def __init__(self, item_name="content", content=""):
        super().__init__()
        query = {"match": {item_name: {"query": content}}}
        self.query["standard"]["query"] = query


class RRF_Exists_Retriever(RRF_Retriever):
    """
    Retriever that boosts documents containing a specified field.
    """

    def __init__(self, field: str, boost: float = 1.0):
        super().__init__()
        self.query["standard"]["query"] = {"exists": {"field": field, "boost": boost}}


class RRF_Semantic_Retriever(RRF_Retriever):
    def __init__(self, item_name="semantic", content=""):
        super().__init__()
        query = {
            item_name: {
                "field": "semantic",
                "query": content,
            }
        }
        self.query["standard"]["query"] = query


class RRF_Vector_Retriever(RRF_Retriever):
    """
    Wrapper for dense-vector retrieval.
    """

    def __init__(self, vector_field="semantic", query_vector=None):
        super().__init__()
        # Remove the parent empty standard query to avoid Elasticsearch parsing errors.
        if "standard" in self.query:
            del self.query["standard"]

        # Dense-vector fields must not be queried with ordinary match or semantic clauses.
        # Use the knn query syntax instead.
        knn_query = {
            "field": vector_field,
            "query_vector": query_vector,  # Query vector generated by the embedding model.
            "k": 10,  # Number of nearest-neighbor documents to retrieve.
            "num_candidates": 100,  # Number of candidates per shard, typically around 10x k.
        }

        # In the RRF (Reciprocal Rank Fusion) architecture,
        # the vector query is usually combined with standard queries as a separate branch.
        # This wrapper assumes the parent query structure supports direct knn assignment.
        self.query["knn"] = knn_query
